### ISSUE TITLE
trouble starting on mac yosemite through haxelib

### ISSUE THREAD

**Issue by lewislepton** [HaxeIDE/HIDE#209]
alright.

ive tried a few times in getting this to work, but am getting nowhere.
this is my output on getting it to run, but dont know what to do. im running on yosemite 10.10.02, with the latest public haxe

![screen shot 2015-05-29 at 23 01 15](https://cloud.githubusercontent.com/assets/11299322/7893701/32dc6c8a-0658-11e5-9e05-ab150cb452a7.png)

**Comment by as3boyan** [comment]
As a workaround, you can try to download `node-webkit` manually from https://github.com/nwjs/nw.js/
and extract contents to haxelib `lib\node-webkit\1,0,7\bin`

**Comment by lewislepton** [comment]
hmmm. im trying. but still the same

![screen shot 2015-05-30 at 13 09 53](https://cloud.githubusercontent.com/assets/11299322/7897266/30e40fa8-06cd-11e5-988a-28d8b6c662ea.png)

**Comment by lewislepton** [comment]
still troubles. how can i fix it.

thanks

**Comment by lewislepton** [comment]
HA, thanks. that worked, just kept saying 'no' for the update and that worked ;)

![screen shot 2015-05-30 at 17 33 38](https://cloud.githubusercontent.com/assets/11299322/7898250/13646f52-06f2-11e5-89e2-45969e073f96.png)
